# Generated by Django 4.2.1 on 2023-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0002_remove_material_matunidadmedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudelemento',
            name='solFechaHoraFin',
            field=models.DateTimeField(db_comment='Fecha hora fin en los que se usara los elementos', null=True),
        ),
    ]
